package com.arthur.newsapp.util

const val API_KEY = "75b51ff768ea44e7bd7be7d095c5f054"
const val BASE_URL = "https://newsapi.org/"
val COUNTRY_CODES = hashMapOf(
    "Арабские эмираты" to "ae",
    "Аргентина" to "ar",
    "Австрия" to "at",
    "Австралия" to "au",
    "Бельгия" to "be",
    "Болгария" to "bg",
    "Бразилия" to "br",
    "Канада" to "ca",
    "Швейцария" to "ch",
    "Китай" to "cn",
    "Колумбия" to "co",
    "Куба" to "cu",
    "Чехия" to "cz",
    "Германия" to "de",
    "Египт" to "eg",
    "Франция" to "fr",
    "Великобритания" to "gb",
    "Греция" to "gr",
    "Гонконг" to "hk",
    "Венгрия" to "hu",
    "Индонезия" to "id",
    "Ирландия" to "ie",
    "Израиль" to "il",
    "Индия" to "in",
    "Италия" to "it",
    "Япония" to "jp",
    "Корея" to "kr",
    "Литва" to "lt",
    "Латвия" to "lv",
    "Морокко" to "ma",
    "Мексика" to "mx",
    "Малайзия" to "my",
    "Нигерия" to "ng",
    "Нидерланды" to "nl",
    "Норвегия" to "no",
    "Новая Зеландия" to "nz",
    "Филиппины" to "ph",
    "Польша" to "pl",
    "Португалия" to "pt",
    "Румыния" to "ro",
    "Сербия" to "rs",
    "Россия" to "ru",
    "Саудовская Аравия" to "sa",
    "Швеция" to "se",
    "Сингапур" to "sg",
    "Словения" to "si",
    "Словакия" to "sk",
    "Таиланд" to "th",
    "Турция" to "tr",
    "Китайская Республика" to "tw",
    "Украина" to "ua",
    "США" to "us",
    "Венесуэла" to "ve",
    "Замбия" to "za"
)